### ISSUE TITLE
overkiz auth uri is hardcoded to Europe region

### ISSUE THREAD

**Issue by erudita** [bitlush/hubitat#2]
Background: Per Somfy Developer https://github.com/Somfy-Developer/Somfy-TaHoma-Developer-Mode
There are different URLs depending on the region of registration.

> ha101-1.overkiz.com (Europe, Middle East and Africa)
> ha201-1.overkiz.com (Asia and Pacific)
> ha401-1.overkiz.com (North America)

Issue:
the driver is hardwired to use ha101-1.
Some users (e.g. me), have registrations outside of Europe.

Example:
I have a registration for Australia which only works on [ha201-1](https://ha201-1.overkiz.com)

**Comment by bitlush** [comment]
This feature has been added.
